### ISSUE TITLE
Check if file is exist

### ISSUE THREAD

**Issue by MapkMapk** [cooffeeRequired/skJson#1]
**Suggestion**

It would be nice to add the ability to check if the file exists

**Why?**

To save servers RAM, it would be more efficient to distribute information about a large number of objects (for example, players) into several files. if each player contains 100 lines of information, and there will be several hundred of them, it would be better to save their data to different files and load as needed , but for this you first need to determine if the file with information about the player exists or not yet

**Other**

I really miss a function to check if a file exists, to see if it can be read or not

**Comment by cooffeeRequired** [comment]
Hi there, this feature will be added in new release, But at this point the separate expression 'newJsonFile' checks if the file exists and if it does you get an error message.

Sincerely coffee.👋
