### ISSUE TITLE
Json size is can't calculate

### ISSUE THREAD

**Issue by gangulwolfs** [cooffeeRequired/skJson#104]
function questvalue(desc: text, json: json):: text:
	set {_a} to json size of {_json}
	set {_i} to "0" parsed as integer
	broadcast "%{_json}% , %{_a}%"
	if json size of {_a} > 0:
		add 1 to {_i}
		broadcast "LOL"

{_json} size is 6. but, this(if json size of {_a} > 0:) operation does not work.

![2024-07-04_18 38 08](https://github.com/cooffeeRequired/skJson/assets/63837112/5c4cf5b0-e37f-4456-a1cd-d31364e05d57)

**Comment by gangulwolfs** [comment]
also. if {_a} > 0: The same goes for it.

function not work.

Bukkit version: This server is running Paper version git-Paper-484 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4445d23)
Skript version: 2.8.7

**Comment by cooffeeRequired** [comment]
What do you close it ? Did you figure out?

**Comment by gangulwolfs** [comment]
Because I didn't think it was a bug because once it was converted to text, it could be used normally.
(Korean language: 왜냐하면 한 번 텍스트로 변환을 거치면 정상적으로 사용할 수 있었기에 버그라 생각을 하지 않았습니다.)
