### ISSUE TITLE
skJson doesn't work in java 22

### ISSUE THREAD

**Issue by Acult** [cooffeeRequired/skJson#106]
Using minecraft 1.16.5 mohist, Skript 2.9.1
skJson fails to load on server start: 
https://pastebin.com/xYTQXwV2

**Comment by cooffeeRequired** [comment]
Mohist arent supported

**Comment by Acult** [comment]
It's not a mohist issue, anyways it was a java problem, skjson is not compatible with java 22 so i had to revert to an older version, now it works.

**Comment by cooffeeRequired** [comment]
Wierd cause skjson od build on 22 java
