### ISSUE TITLE
Enchantments do not work with 'give'

### ISSUE THREAD

**Issue by Stuntlover-TM** [cooffeeRequired/skJson#108]
Hey, I was making a system to save items to a database using skJson, which works fine except for one thing.
Saving an item with an enchantment and loading it again removes the enchantment, even the official example in the README.md file does not work:

```vb
set {_item} to diamond sword named "Test"
set lore of {_item} to "&6Gold" and "&7Silver"
enchant {_item} with Sharpness 5
set {_json_item} to json from {_item}
    
give {_json_item} to player
```

The name and lore stay correct, but the enchantment is not saved. I am on the most recent skJson version and Minecraft version 1.21.1.
The interesting thing is that if I display `{_data}`, it does show that it has the enchantment (as shown in the attached image)
![image](https://github.com/user-attachments/assets/58d02fcf-3e4e-433a-aabf-ee6c03ad3bfa)

**Comment by cooffeeRequired** [comment]
Known issue, i will fix it soon

**Comment by Stuntlover-TM** [comment]
Thanks for the quick response, looking forward to the fix!

**Comment by cooffeeRequired** [comment]
#109
