### ISSUE TITLE
Broken Map JSON Syntax

### ISSUE THREAD

**Issue by baylorhenshaw** [cooffeeRequired/skJson#11]
**Describe the bug**
When attempting to map JSON into a Skript variable with the `map json` syntax, the server implodes.

**To Reproduce**
1. Run an effect command and read the error. An example is below.
`!map json from "{""_id"": ""93eb06cd-0a1e-4d04-affe-81a59b632815"", ""username"": ""Baezor""}" to {test::*}`

**Expected behavior**
The JSON should be mapped to a variable, but it stops the rest of the script from running instead.

**Screenshots**
![Screen Shot 2023-01-22 at 1 27 28 PM](https://user-images.githubusercontent.com/64096464/213935991-345a6e35-a0ef-457a-9d28-457be2c3ca06.png)
![Screen Shot 2023-01-22 at 1 30 26 PM](https://user-images.githubusercontent.com/64096464/213936127-d561a9a3-2f7f-4675-b36d-f453ddaac74d.png)

**Versions**
 - Skript Version: `2.6.4`
 - skJson Version: `2.6.0`
 - Server Version: `git-Filter+-"9247091" (MC: 1.19.2)*`

**Additional context**

**Comment by cooffeeRequired** [comment]
I'll take a look at it right now, cause you don't have SkBee.
