### ISSUE TITLE
Removing Entries from JSON-Lists (Counterpart of Appending)

### ISSUE THREAD

**Issue by ExCorde** [cooffeeRequired/skJson#15]
```
    "permissions": {
      "members_allowed_to_build": [
        "933334f8-a330-4551-81dd-aafb677a8186"
      ]
    },
```
    
Effect that makes it possible, to remove entries of json-maps. 
At the moment, this is only possible via mapping. 
Removing json values (strings etc.) is possible already.

**Comment by cooffeeRequired** [comment]
Thanks for the report corrected at the moment, please check 
https://github.com/cooffeeRequired/skJson/pull/16
Thank you kindly coffee👋
