### ISSUE TITLE
Item Conversion in JSON

### ISSUE THREAD

**Issue by baylorhenshaw** [cooffeeRequired/skJson#18]
**Is your feature request related to a problem? Please describe.**
When converting an item variable into JSON, all you get is useless information.

**Describe the solution you'd like**
I think it would be a great if skJson supported converting items to and from JSON.

**Describe alternatives you've considered**
There are ways to store different parts of an item with the ID and NBT data, but native support for this would be nice for things such as inventory storage and other use cases.

**Additional Context**
The current result you get from skJson looks like this:
```json
{
   "types": [
    {
      "isAnything": false,
      "itemForm": false,
      "isAlias": false,
      "plain": false,
      "itemFlags": 2
    }
  ],
  "all": false,
  "amount": -1
}
```

**Comment by cooffeeRequired** [comment]
Hello what version you have?

**Comment by baylorhenshaw** [comment]
I'm on version `2.6.2`

**Comment by cooffeeRequired** [comment]
What expression do you use?
Because the item serilization its supported

**Comment by baylorhenshaw** [comment]
With effect commands:
```
1. set {-test::*} to stone, apple and stone pickaxe named "&aHello World"
2. broadcast {-test::*}'s form
```
and now I'm getting a massive error
https://paste.gg/p/anonymous/7760e7a3c07c4486905847dd152209b5

**Comment by cooffeeRequired** [comment]
Oh, so form of list, well i will look on it tmr.

**Comment by cooffeeRequired** [comment]
![image](https://user-images.githubusercontent.com/106232282/216022570-529dbe9c-db7d-4259-9a51-f40da8d1d744.png) Fixed already ! Now I'm going to look at the error you sent.

**Comment by cooffeeRequired** [comment]
finished fix.
https://github.com/cooffeeRequired/skJson/releases/tag/2.6.21
