### ISSUE TITLE
JSON-Format is having problems with UTF-8 characters. 

### ISSUE THREAD

**Issue by ExCorde** [cooffeeRequired/skJson#19]
**Describe the bug**
When you use UTF-8 characters in saved strings in a json-file, the output is messy.

**To Reproduce**
```
      "textlines": [
        "&f",
        "               &f &f&lGute Fee:",
        "               &7Du möchtest eine Siedlung gründen? Nun gut.",
        "               &7Ich habe den Kaufvertrag für das Land unter",
        "               &7deinen Füßen mitgebracht. Klicke mit der",
        "               &7rechten Maustaste (RMB) auf mich!",
        " "
      ],
```
**Expected behavior**
The UTF-8 characters should be encoded correctly. 

**Screenshots**
<img width="968" alt="Unbenannt" src="https://user-images.githubusercontent.com/53936268/217820120-f2f2552c-f1c7-4251-b7b4-00f52e7f9a98.PNG">

**Comment by cooffeeRequired** [comment]
Hello, atm i will look on it.

**Comment by cooffeeRequired** [comment]
![image](https://user-images.githubusercontent.com/106232282/218161424-c164a069-16a2-4dd6-8182-1eeb9bbca8f5.png)
Fixed already

**Comment by cooffeeRequired** [comment]
```hs
command try:
    trigger:
        write "🤣" to json file "items/utf8.json"
        ```

**Comment by ExCorde** [comment]
The bug has been fixed and the new version has been tested. Everything works properly. If you have any problems with UTF-8 Encoding, try to add `-Dfile.encoding=UTF-8` to your start.bat / start.sh. 
Example of a start.bat:
```
@echo off
title Server Console (Localhost)
java -Xmx4G -Dfile.encoding=UTF-8 -jar paper.jar -nogui
PAUSE
```
