### ISSUE TITLE
mapped json values not interpretated as strings

### ISSUE THREAD

**Issue by creptor** [cooffeeRequired/skJson#2]
I'm trying to adapt my skript (was already working using an old json interpreter), but I'm having problems in the interpretation of the values for the mapped json, because is not being outputted as strings and instead is saved as json-object (I think).

I would like to know if there's something I’m missing on the conversion or if this could be an improvement on the addon for handling values in the json deserialization.

## Example of problem:
Json
```
{
    "10-31":{
       "lore":[
          "&4Recompensas extras!",
          "&fObtendrás items y más dinero por ser",
          "&f <##eb6123>Halloween&f!"
       ],
       ...
}
```
Code
```skript
map json from {@example_json} to {variable::*}
set {_lore::*} to {variable::10-31::lore::*}
add "" to {_lore::*}
add "&8&l > &8Recompensa perdida" to {_lore::*}
message {_lore::*} to console
```
Output
```shell
[14:03:00 INFO]: "Recompensas extras!"
[14:03:00 INFO]: "Obtendrás items y más dinero por ser"
[14:03:00 INFO]: " Halloween!"
[14:03:00 INFO]:
[14:03:00 INFO]:  > Recompensa perdida
```
**Expected**
```shell
[14:03:00 INFO]: Recompensas extras!
[14:03:00 INFO]: Obtendrás items y más dinero por ser
[14:03:00 INFO]:  Halloween!
[14:03:00 INFO]:
[14:03:00 INFO]:  > Recompensa perdida
```

As you can see, the first 3 results are outputted as something else on the console, and can't be interpreted by skript as strings, so I can't use them on an item lore like I need in this case.

I also tried using something like:
`set {_lore::*} to {variable::10-31::lore::*} as strings`
but it doesn't work.
Probably it could be fixed with a loop function, but it wouldn't be ideal in my case.

**Comment by cooffeeRequired** [comment]
Hi there, you are right everything inside a list::* is interpreted as json. **(JsonObject, JsonPrimitive, JsonArray)**

Do you have Skript-reflect?

**Comment by creptor** [comment]
No, I don't. Is it necessary for the string interpretation or a way to fix it?

I can install it if needed.

**Comment by cooffeeRequired** [comment]
No. It's for get instance of those 
Please download skript-reflect
And execute this code
```v
Broadcast class of {variable::10-31::lore::1}
```

**Comment by creptor** [comment]
This is the output:
```
[15:00:26 INFO]: com.google.gson.JsonPrimitive
[15:00:26 INFO]: "Recompensas extras!"
[15:00:26 INFO]: "Obtendrás items y más dinero por ser"
[15:00:26 INFO]: " Halloween!"
[15:00:26 INFO]:
[15:00:26 INFO]:  > Recompensa perdida
```

**Comment by cooffeeRequired** [comment]
Yeah, as you can see it's **JsonPrimitive**, so gimme sec ill try fix that

**Comment by cooffeeRequired** [comment]
Problem solved, for now I'll give you a temporary script-gson file

![image](https://user-images.githubusercontent.com/106232282/200187729-4ac0bd70-c025-444b-ae2c-467e52dfed1a.png)

```json
{
  "players": {
    "coffeeRequired": {
      "name": "coffee",
      "AnotherElement": ["Some Data here",2,3]
    }
  }
}
```
```vb
on script load:
    set {_data} to json from file "gson/test1.json"
    map json from {_data} to {_data::*}
    set {_a::*} to {_data::players::coffeeRequired::AnotherElement::*}
    broadcast class of {_a::*}
```
[skript-gson-1.1.0-Fix issue 2.zip](https://github.com/cooffeeRequired/skript-gson/files/9946517/skript-gson-1.1.0-Fix.issue.2.zip)

**Comment by creptor** [comment]
Thank you!! That was super fast and it works!

It's still weird because the text contains the " at the start and end, but I can work with that.

Aside from the issue, maybe there should be a way to interprete the primitive based on the type of value defined on the code, like:
`set {_lore::*} to {variable::10-31::lore::*} as strings`
would output:
```
Some Data here
2
3
#java.lang.String
```
and
`set {_lore::*} to {variable::10-31::lore::*} as integers`
would output:
```
Error...
2
3
#java.lang.Integer
```

**Comment by cooffeeRequired** [comment]
Yes, I know it, everything will be fixed in the next version, please look here, you will see all known bugs https://github.com/cooffeeRequired/skript-gson a I'd also like to invite you to a discord https://discord.gg/dsZq5Cs9fd S compliments of Coffee 👋
