### ISSUE TITLE
Giving player item with custom-model-data from json doesn't work -> data gets lost

### ISSUE THREAD

**Issue by ExCorde** [cooffeeRequired/skJson#22]
**Describe the bug**
When I give a player an item with custom-model-data from json, it doesn't work. The custom model data gets lost.

**To Reproduce**

1. Add this code to a skript:
```
Command /givetomato:
    trigger:
        give player apple with custom model data 1 named "&fTomate"

Command /apple:
    trigger:
        set {_apple} to json from player's tool
        broadcast "%{_apple}%"
        give player {_apple}

On rightclick with apple:
    broadcast json from player's tool
```

2. Run /givetomato
3. Hold the given item in your hand
4. Run /apple (json outprint: model data is there)
6. Rightclick with the given item in your hand (json outprint: model data is lost)

**Expected behavior**
The second output should have also custom model data included.

**Comment by cooffeeRequired** [comment]
Already fixed, Issue was comprimite by the rewriting it self.
![image](https://user-images.githubusercontent.com/106232282/218317086-8ea620bb-4ac6-48bb-a076-866948dbde5a.png)

**Comment by ExCorde** [comment]
The bug has been fixed and tested by community tester "ExCorde". 
The issue was also accruing when using the recipe effect from SkBee.
