### ISSUE TITLE
Adding RE-APPENDING Syntax

### ISSUE THREAD

**Issue by ExCorde** [cooffeeRequired/skJson#23]
**Is your feature request related to a problem? Please describe.**
Removing entries from json files requires more complicated syntax then appending. 

**Describe the solution you'd like**
A syntax called "reappending" would make it easier to handle files and json formats. It does the same like the appending syntax, 
but removes instead of adds. 

**Additional context**
(https://skripthub.net/docs/?id=8489)

**Comment by cooffeeRequired** [comment]
![image](https://user-images.githubusercontent.com/106232282/219462385-6f07baae-fb4a-4ed2-83d2-6158a4a2e323.png)
Fixed.

**Comment by cooffeeRequired** [comment]
The current syntax is kind of similarry like the Append
