### ISSUE TITLE
Custom-Model-Data gets lost with minecraft item type: "bundle"

### ISSUE THREAD

**Issue by ExCorde** [cooffeeRequired/skJson#24]
**Describe the bug**
Custom-Model-Data gets lost with minecraft item type: "bundle"

**To Reproduce**
1. Save a bundle to json.
2. Give a bundle from json.

When saving: 
`[skJson] [STDOUT] SOURCE: ItemStack{BUNDLE x 1, BUNDLE_META:{meta-type=BUNDLE, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Paket"}],"text":""}, lore=[{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"An: "},{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Kalabweg 1, Daria"}],"text":""}], custom-model-data=1, items=[ItemStack{SPRUCE_WOOD x 64}]}}`

When giving:
`[10:10:34 INFO]: [skJson] [STDOUT] SOURCE: ItemStack{BUNDLE x 1, BUNDLE_META:{meta-type=BUNDLE, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Paket"}],"text":""}, lore=[{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"An: "},{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Kalabweg 1, Daria"}],"text":""}], items=[ItemStack{SPRUCE_WOOD x 64}]}}`

**Expected behavior**
The custom model data should get loaded correctly.

**Comment by cooffeeRequired** [comment]
![image](https://user-images.githubusercontent.com/106232282/219871496-86eee020-4278-4de8-8ace-4ca08e892c45.png)
Fixed version : https://github.com/cooffeeRequired/skJson/releases/tag/pre-release-2.7.0

**Comment by ExCorde** [comment]
The bug was fixed and tested by community tester "ExCorde".
