### ISSUE TITLE
Java 8 support!

### ISSUE THREAD

**Issue by yzhyyyyy** [cooffeeRequired/skJson#25]
**Is your feature request related to a problem? Please describe.**
Alot of servers use java 8, and it would be super cool if you made a version, or just added support for it. Some features might not work, but if the "main" part still works it would be cool!

**Describe the solution you'd like**
java 8 support :D

**Describe alternatives you've considered**
Nothing

**Additional context**
Nope

**Comment by cooffeeRequired** [comment]
Hello, At this moment i looking on it

**Comment by cooffeeRequired** [comment]
![image](https://user-images.githubusercontent.com/106232282/221289712-d0667788-6c82-4fd6-85a5-cc673260d6f7.png)
I'm sorry the core of skJson can't be run on Java version 1.8 (8)
