### ISSUE TITLE
Issue with changing multiple values with nested values

### ISSUE THREAD

**Issue by RedstoneGamer54** [cooffeeRequired/skJson#4]
Issues when trying to change multiple values with nested values

```
function addPlayerData(p: offlineplayer):
    set {_json} to new json from file "plugins/skript/data/base.json"
    #firstJoin is the nested value
    change {_json} values "uuid", "firstJoin" to ({_p}'s uuid), unix timestamp of now
```

`"uuid"` will get set to the unix timestamp

**Comment by cooffeeRequired** [comment]
Already fixed.

```diff
- Line 87 [EffChangeJson.java] changed = GsonUtils.change(element, from[0].toString(), to[i], tag == 1 ? GsonUtils.Type.KEY : GsonUtils.Type.VALUE);

+ Line 87 [EffChangeJson.java] changed = GsonUtils.change(element, from[i].toString(), to[i], tag == 1 ? GsonUtils.Type.KEY : GsonUtils.Type.VALUE);
```
![image](https://user-images.githubusercontent.com/106232282/205616801-b54beb42-a25f-4a0a-a56f-996d0c2ee012.png)

Sincerely coffee 👋.
[skript-gson-1.4.0-(Fix - Nested Values or Keys).zip](https://github.com/cooffeeRequired/skript-gson/files/10153284/skript-gson-1.4.0-.Fix.-.Nested.Values.or.Keys.zip)
