### ISSUE TITLE
[Suggestion] Remove the * when mapping a json -> variables.

### ISSUE THREAD

**Issue by MinecraftNight4** [cooffeeRequired/skJson#45]
When mapping a json to variables, it always adds a * as the first element.

**json:**
{data:[{"msg": 1},{"msg": 2},{"msg": 3}]}

**Skript Var:**
{_temp::data::*} -> [Doesn't return data]
{_temp::data::1::msg} -> 1
{_temp::data::2::msg} -> 2
{_temp::data::3::msg} -> 3

**Comment by cooffeeRequired** [comment]
What do you mean?
can you show me short vid. or some screens and runtime code?

**Comment by MinecraftNight4** [comment]
This is the script:
```
on load:
	send a "get" request to "https://raw.githubusercontent.com/MinecraftNight4/bot_muse/bd30274c7411771edd403ec419dc90f55e58f999/hello_bot.json"
	set {_get} to last response's body
	map {_get} to {_json::*}
	broadcast indices of {_json::hello::*}
```

And this is the output
![image](https://user-images.githubusercontent.com/42017416/228644172-a7cb2177-f36e-4a7a-a349-5695b93c2a6b.png)

**Comment by cooffeeRequired** [comment]
oh i see, you can filter out by `where [input is not "*"]`

**Comment by cooffeeRequired** [comment]
also you can use a skJson get/post request

**Comment by MinecraftNight4** [comment]
Okay, I'll be using that then(The filter). And I'm currently using an outdated version of SkJson. The latest update will allow me to simplify some complex scripts that I have.

That's it for now.
