### ISSUE TITLE
Issue with the map function D:

### ISSUE THREAD

**Issue by nightway1** [cooffeeRequired/skJson#5]
When I use the map json funcion, in-game nothing appears.
but in the console it directly explodes with this message.

![image](https://user-images.githubusercontent.com/98564343/206809088-ff92ba6f-44ea-4990-9c22-523952fcd70e.png)

![image](https://user-images.githubusercontent.com/98564343/206808622-93254567-660b-4e34-a109-bef14d6ab167.png)

![image](https://user-images.githubusercontent.com/98564343/206807752-617c4c59-1e69-4409-93fa-a93e3d7940aa.png)

if it is so long that it required like 3 screenshots

In the errors it says that the problem is using reqn but I know that the problem is from the gson script because it only happens when I update it to its latest version, it worked moderately correctly in version 1.1.0.

I had to update it because the json mapping function works strangely in certain cases instead of returning the value it should, it returned a true, and I wanted to see if it was working in the new version.

---------------------------------------------------------------------------------------------------------

Minecraft version: 1.19.2

Server software: purpur

Skript version: 2.6.4

Skript gson version: 1.4.0

**Comment by cooffeeRequired** [comment]
Hello there, can you please send me the `sk info` also the `executed command` or code from file
Thank! 

👋
