### ISSUE TITLE
the official example of EffJsonToSkriptList is not working

### ISSUE THREAD

**Issue by yhdev7935** [cooffeeRequired/skJson#60]
Plugin Versions: Skript 2.7.0-beta3, SkJson 2.8.6

## Step to reproduce

1. 
![image](https://github.com/SkJsonTeam/skJson/assets/55119171/c58e159d-6c67-4088-a55f-7ab6b73b4261)
![image](https://github.com/SkJsonTeam/skJson/assets/55119171/8dc25b31-18c9-4809-a351-d40e04724657)

**Comment by ghost** [comment]
Hello there, you have wrong input.. That `{"test": "test2": {}}` aren't valid input, also you forget `json from string`

**Comment by yhdev7935** [comment]
Then, you have to fix your official examples.
![image](https://github.com/SkJsonTeam/skJson/assets/55119171/4b9ea063-bbe4-4007-bf5e-f9b78dfda5b1)
