### ISSUE TITLE
[Suggestion]: Save invalid responses as nested json

### ISSUE THREAD

**Issue by MinecraftNight4** [cooffeeRequired/skJson#61]
In some webrequests, it is not always possible to get a response in valid json format.

For example, these may appear in another format or have part of the json malformed:
```json
{\"message\":\"this json is broken},
This is just a string, nothing important...
```

I think in these situations, instead of destroying the response, it should be stored anyway, but inside a nested json, in case you want to use the response anyway:
```json
["{\"message\":\"this json is broken},"]
["This is just a string, nothing important..."]
```

**Comment by ghost** [comment]
Done

**Comment by ghost** [comment]
Working on it for 2.8.6
