### ISSUE TITLE
[Suggestion] Json-Watcher event

### ISSUE THREAD

**Issue by MinecraftNight4** [cooffeeRequired/skJson#62]
It would be useful in some occasions to have a trigger when a Json-Watcher executes a save.
For example:
```
on json-watcher saves:
	broadcast event-json -> This one have the full saved-json
	broadcast event-link -> This is the Link ID
```

**Comment by ghost** [comment]
Thank for suggestion, Working on it ATM!

**Comment by ghost** [comment]
For version `2.8.6` the event cannot be implemented due Skript api
For version `2.9` was implemented successfully

https://github.com/SkJsonTeam/skJson/commit/17b98519e1edc07ec4f3c66014596d52786baa0a
