### ISSUE TITLE
Error occurred while enabling SkJson v2.9

### ISSUE THREAD

**Issue by Teric7** [cooffeeRequired/skJson#73]
I was told to open a gh issue. 

[2023-09-21-5.log](https://github.com/SkJsonTeam/skJson/files/12683023/2023-09-21-5.log)

That's the whole server log.

**Comment by envizar** [comment]
Try using [Paper](https://papermc.io/downloads/all)
(Just now I saw the discussion in the help discord forum)

**Comment by ghost** [comment]
Hello there, use a `skjson-2.9-spigot.jar`
This jar is modified specifically for Spigot servers.
https://github.com/SkJsonTeam/skJson/releases/tag/2.9
https://github.com/SkJsonTeam/skJson/releases/download/2.9/skJson-2.9-spigot.jar
![image](https://github.com/SkJsonTeam/skJson/assets/130649230/e2d52b3c-99db-435b-a5a0-eb7b07cfbc85)
