### ISSUE TITLE
Can't read unicode after map

### ISSUE THREAD

**Issue by Tojefin** [cooffeeRequired/skJson#79]
![image](https://github.com/SkJsonTeam/skJson/assets/39239196/eb5e3645-8066-41e0-a571-ce83949d2c32)
![image](https://github.com/SkJsonTeam/skJson/assets/39239196/25d4b23f-d5c6-401d-9630-7a164d0ecce2)

**Comment by ghost** [comment]
Hello there, so russian chars are not correct right
Can you provide `/sk info` & `/about skjson` & `/version`

**Comment by Tojefin** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/39239196/c2829124-1c86-4c19-ac79-b3378911a356)
![image](https://github.com/SkJsonTeam/skJson/assets/39239196/4f7825fc-72e5-4b0c-8507-4bfd1373a4e8)
![image](https://github.com/SkJsonTeam/skJson/assets/39239196/31ce29b0-37f1-4f1b-b5d5-0ebc91c95116)

I fix it by change encoding of json file from UTF8 to Windows 1251
![image](https://github.com/SkJsonTeam/skJson/assets/39239196/f93efdff-ffa1-45de-b258-9b2ae9d3b1a2)

**Comment by cooffeeRequired** [comment]
Hello there, the issue causing becouse of Pufferfish.. 
In the few days i will check it.

**Comment by cooffeeRequired** [comment]
Are you there?

**Comment by Tojefin** [comment]
Yes, can I help you?

**Comment by ghost** [comment]
Can you tried the latest version please?

**Comment by cooffeeRequired** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/106232282/edf54a40-1e3f-444a-9057-7fbbebad98a7)
```
[23:41:57 INFO]: SkJson revision version: e68c14433
[23:41:57 INFO]: Description: 
                  -  SkJson is module/addon for well-known programming language Skript for minecraft world.
                  -  SkJson is used for parsing JSON data from any object like website api,
                  -  skript object e.g. (item, location), file, yaml-file, text.
[23:41:57 INFO]: SkJson version: 2.9.6
[23:41:57 INFO]: Author: [CoffeeRequired]
[23:41:57 INFO]: API-version: 1.16
[23:41:57 INFO]: Website: https://www.skjson.xyz/
[23:41:57 INFO]: GitHub: https://www.github.com/SkJsonTeam/SkJson
```

```
[23:42:10 INFO]: Checking version, please wait...
[23:42:10 INFO]: Current: git-Purpur-2084 (MC: 1.20.2)*
* You are 11 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

**Comment by cooffeeRequired** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/106232282/0751cebc-ba43-42ee-ad30-80ec5905cba8)
