### ISSUE TITLE
map %json|string% to %objects% doesn't work

### ISSUE THREAD

**Issue by fsdghyiusfdhiusodf** [cooffeeRequired/skJson#82]
`on load:
  make GET request to "https://api.minehut.com/server/aserver?byName=True":
    save incorrect response: true
    lenient: true
    save:
      content:  {-content}
  map {-content} to {test::*}
  broadcast {-content}
  broadcast "%{test::*}%" # without "%%" doesn't send anything
  `
output:
{a very long json}
<none>

**Comment by ghost** [comment]
can you format it better for eg. 

```applescript
on script load:
 .... 
 ```

**Comment by ghost** [comment]
Also send me your version of skJson `skjson about` and version of your server

**Comment by ghost** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/130649230/c6508181-3e25-4729-9f8f-b6523328fe16)

```applescript
on load:
    make GET request to "https://api.minehut.com/server/aserver?byName=True":
        save incorrect response: true
        lenient: true
        save:
            content: {_content}

    #send {_content}
    map {_content} to {_test::*}

    send {_test::server::owner}

```

seems everything working.

**Comment by fsdghyiusfdhiusodf** [comment]
Ah, it seems im dumb and forgot the bug that’s existed in skript lists forever (that being ::* not getting sub-objects). Somehow I never double checked variables.csv

**Comment by ghost** [comment]
So, i can close it?

**Comment by fsdghyiusfdhiusodf** [comment]
yes
