### ISSUE TITLE
 "write to json file" is broken

### ISSUE THREAD

**Issue by envizar** [cooffeeRequired/skJson#84]
When trying to write to existing file, it prints `[SkJson] WARN Cannot create a file plugins/Skript/scripts/test/data.json cause the file already exists.` in console

SkJson: 3.0.0
Skript: 2.8.0-pre2
Paper: 1.20.4 0ae58c0

**Comment by ghost** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/130649230/c9a72b4b-afe7-4e1b-9be1-22c8b7657c46)
Fixed the method was messup
