### ISSUE TITLE
values of %json% is broken

### ISSUE THREAD

**Issue by envizar** [cooffeeRequired/skJson#86]
values of %json% is broken
```
on load:
	set {_json} to @{a: 1, b: 2}
	broadcast values of {_json}
```
![изображение](https://github.com/SkJsonTeam/skJson/assets/87126318/191d9078-1454-4779-b44e-125f413db0bc)

**Comment by ghost** [comment]
can you send skjson about?

**Comment by envizar** [comment]
![изображение](https://github.com/SkJsonTeam/skJson/assets/87126318/58a57896-aa8a-48bd-a1a1-71a4fedab061)

**Comment by ghost** [comment]
Strange, ill make new revision and update the `.jar` can you redownload it?

**Comment by ghost** [comment]
[JAR](https://github.com/SkJsonTeam/skJson/releases/tag/3.0.2-IO)
please redownload that jar and send skjson about after that

**Comment by envizar** [comment]
Now it works

**Comment by ghost** [comment]
Can you send revision version? i mean Skjson about

**Comment by envizar** [comment]
![Screenshot_2024-01-21-00-00-21-924-edit_com.yandex.browser.jpg](https://github.com/SkJsonTeam/skJson/assets/87126318/a9c4d5ae-f858-40fb-bc61-b494551f8159)

**Comment by ghost** [comment]
Oh, i forgot upload updated file :D that is the reason, okey fine, issue resolved and closed
