### ISSUE TITLE
Strange bug with some symbols

### ISSUE THREAD

**Issue by envizar** [cooffeeRequired/skJson#88]
test.json:
![изображение](https://github.com/SkJsonTeam/skJson/assets/87126318/a1c031e2-4495-413e-9bb1-d43b410c4228)

![изображение](https://github.com/SkJsonTeam/skJson/assets/87126318/7bf28161-7cbd-47ef-a016-9738bf35ebf0)

Using latest jar file (skJson v3.0.2-IO)
Operating system: Windows 11 (I test everyhing on my localhost server)
On linux it works withous issues

**Comment by cooffeeRequired** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/106232282/5563a419-f1f5-451b-9f02-9d7b203a712d)
Fixed, the error was in the file processing **3.0.3**
