### ISSUE TITLE
problem with writing quotes in json

### ISSUE THREAD

**Issue by pex666** [cooffeeRequired/skJson#90]
I'm trying to save nbt in one line, but if  nbt is too large, then  get this (pic)

![skript](https://github.com/cooffeeRequired/skJson/assets/48218192/3cfc59dd-4499-4aec-a077-789ff32c83df)
![skjson](https://github.com/cooffeeRequired/skJson/assets/48218192/c1a89bc9-7785-4c1a-9514-96f3701e8173)

SkJson v3.0.3
Skript v2.8.2
SkBee v3.3.0

**Comment by cooffeeRequired** [comment]
Thank you, ill check it now

**Comment by cooffeeRequired** [comment]
Hello there.
Can you provide the code snippet? I cannot replicate that.

**Comment by pex666** [comment]
Hello!

command /addtrade:
	permission: OP
	trigger:
		set {_jt} to json from file "/plugins/Skript/scripts/json/trader.json" # this is my json file
		set {_slot0} to full nbt compound of slot 0 of player
		set {_slot1} to full nbt compound of slot 1 of player
		set {_slot2} to full nbt compound of slot 2 of player 
		set {_n} to 0
		loop values "trade::%{_n}%" of {_jt}:
			set {_n} to json-key parsed as integer		
		add 1 to {_n}
		set value of json object "trade::0::%{_n}%::0::nbt" in {_jt} to "'%{_slot0}%'"
		set value of json object "trade::0::%{_n}%::1::nbt" in {_jt} to "'%{_slot1}%'"
		set value of json object "trade::0::%{_n}%::2::nbt" in {_jt} to "'%{_slot2}%'"
		write {_jt} to json file "/plugins/Skript/scripts/json/trader.json"

But! you need an already existing json file
fore example: trader.json:

{
  "trade": [
    {
      "1": [
        {
          "nbt": "{Count:32b,id:\"minecraft:arrow\"}"
        },
        {
          "nbt": "{Count:8b,id:\"minecraft:emerald\"}"
        },
        {
          "nbt": "{Count:16b,id:\"minecraft:tipped_arrow\",tag:{Potion:\"minecraft:weakness\"}}"
        }
      ]}]}

**Comment by cooffeeRequired** [comment]
> Hello!
> 
> command /addtrade: permission: OP trigger: set {_jt} to json from file "/plugins/Skript/scripts/json/trader.json" # this is my json file set {_slot0} to full nbt compound of slot 0 of player set {_slot1} to full nbt compound of slot 1 of player set {_slot2} to full nbt compound of slot 2 of player set {_n} to 0 loop values "trade::%{_n}%" of {_jt}: set {_n} to json-key parsed as integer add 1 to {_n} set value of json object "trade::0::%{_n}%::0::nbt" in {_jt} to "'%{_slot0}%'" set value of json object "trade::0::%{_n}%::1::nbt" in {_jt} to "'%{_slot1}%'" set value of json object "trade::0::%{_n}%::2::nbt" in {_jt} to "'%{_slot2}%'" write {_jt} to json file "/plugins/Skript/scripts/json/trader.json"
> 
> But! you need an already existing json file fore example: trader.json:
> 
> { "trade": [ { "1": [ { "nbt": "{Count:32b,id:"minecraft:arrow"}" }, { "nbt": "{Count:8b,id:"minecraft:emerald"}" }, { "nbt": "{Count:16b,id:"minecraft:tipped_arrow",tag:{Potion:"minecraft:weakness"}}" } ]}]}

Thank you, can you provide also those itemns? or Skript what will generate those with the nbts?

**Comment by pex666** [comment]
Sorry, I didn't understand a little

you need to put items in the slots in the game
enter the command and you get the following Json Object

**Comment by pex666** [comment]
just try inserting regular items and then using items with multiple enchantments and custom names

**Comment by cooffeeRequired** [comment]
i mean the items what containts the nbts.

**Comment by pex666** [comment]
all items contain nbt, but the more information an item contains, such as enchantments or custom names, custom tags, the more nbt it contains

"6": [
        {
          "nbt": "{Count:16b,id:\"minecraft:diamond\"}"
        },
        {
          "nbt": "{Count:64b,id:\"minecraft:emerald\"}"
        },
        {
          "nbt": "{Count:1b,id:\"minecraft:bow\",tag:{Damage:0,Enchantments:[{id:\"minecraft:flame\",lvl:1s},{id:\"minecraft:infinity\",lvl:1s},{id:\"minecraft:power\",lvl:3s},{id:\"minecraft:unbreaking\",lvl:3s}]}}"
        }
      ]

**Comment by cooffeeRequired** [comment]
Thank you

**Comment by cooffeeRequired** [comment]
Hello there, Checked that and the result is, the parser will try sanitize them

![image](https://github.com/cooffeeRequired/skJson/assets/106232282/08580425-9833-4845-b92c-07ca064c051c)

but you actually did it you put the ' here

![image](https://github.com/cooffeeRequired/skJson/assets/106232282/8cf7cf4c-b27f-4af5-8b7d-1d7a124e7631)

**Comment by cooffeeRequired** [comment]
![image](https://github.com/cooffeeRequired/skJson/assets/106232282/25a0cdca-bc91-47ea-b88b-83d729518011)

```applescript
command /addtrade:
    permission: OP
    trigger:
        set {_jt} to json from file "plugins/SkJson/test.json" # this is my json file
        set {_slot0} to full nbt compound of slot 0 of player
        set {_slot1} to full nbt compound of slot 1 of player
        set {_slot2} to full nbt compound of slot 2 of player
        set {_n} to 0

        send {_jt} with pretty print to console

        write {_jt} to json file "plugins/SkJson/trader.json"
        loop values "trade::%{_n}%" of {_jt}:
            send json-key to console
            set value of json object "trade::0::%{_n}%::0::nbt" in {_jt} to {_slot0}
            set value of json object "trade::0::%{_n}%::1::nbt" in {_jt} to {_slot1}
            set value of json object "trade::0::%{_n}%::2::nbt" in {_jt} to {_slot2}
        write {_jt} to json file "plugins/SkJson/trader.json"
```

works perfectly fine
