### ISSUE TITLE
Conflicts with skript yaml

### ISSUE THREAD

**Issue by 0xRty** [cooffeeRequired/skJson#91]
skjson lists get blocked by skript yaml
none of the following broadcasts work when skript yaml is also installed

```
broadcast "&e%value "value" of {_results::1}%"
    loop {_results::*}:
        broadcast "%value "value" of loop-value%"
```

And I get this skript yaml error in  console

`[skript-yaml] No yaml by the name 'null' has been loaded`

**Comment by cooffeeRequired** [comment]
So that happens on line loop? or `value of?`

**Comment by 0xRty** [comment]
It happens on both broadcast lines
so
`broadcast "&e%value "value" of {_results::1}%"`
and
` broadcast "%value "value" of loop-value%"`
